server:
  port: 2025
spring:
  profiles:
    active: ${SPRING_PROFILE_ACTIVE:local}
  application:
    name: "cards"
  config:
    import: "optional:configserver:http://localhost:8071/"

management:
  endpoints:
    web:
      exposure:
        include: "*"