##spring:
##  datasource:
##    url: jdbc:mysql://localhost:3307/microservice101
##    username: dKar101
##    password: serviceAdmin
##  jpa:
##    hibernate:
##      ddl-auto: update
##    show-sql: true
#
#accounts:
#  message: "Welcome to accounts service -(local)"
#  contactDetails:
#    name: "Dibyendu Kar"
#    email: "d@gmail.com"
#  customerCare:
#    - (+91) 1291871609
#    - (+91) 3120190816