#server:
#  port: 2023
#
#spring:
#  datasource:
#    url: jdbc:mysql://192.168.1.8:3306/microservice101
#    username: dKar101
#    password: serviceAdmin@123
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true

#cards:
#  message: "Welcome to cards service -(ubuntu server)"
#  contactDetails:
#    name: "Dibyendu Kar"
#    email: "dk@gmail.com"
#  customerCare:
#    - (+91) 9090890909
#    - (+91) 8778909087