#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3307/microservice101
#    username: dKar101
#    password: serviceAdmin
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true

loans:
  message: "Welcome to loans service -(local)"
  contactDetails:
    name: "Dibyendu Kar"
    email: "b@gmail.com"
  customerCare:
    - (+91) 9101021010
    - (+91) 8288191029