server:
  port: 2023

spring:
  datasource:
    url: jdbc:mysql://192.168.1.8:3306/microservice101
    username: dKar101
    password: serviceAdmin@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

accounts:
  message: "Welcome"
  contactDetails:
    name: "Dibyendu Kar"
    email: "d@gmail.com"
  customerCare:
    - (+91) 1291871609
    - (+91) 3120190816