server:
  port: 2024

spring:
  profiles:
    active: ${SPRING_PROFILE_ACTIVE:local}
  application:
    name: "loans"
  config:
    import: "optional:configserver:http://localhost:8071/"

management:
  endpoints:
    web:
      exposure:
        include: "*"