##declaring base image containing java runtime
#FROM openjdk:17-jdk-slim
#
##Info about who maintains this image
#MAINTAINER dibyenduKar
#
##Adding the application's jar to the image
#COPY target/account-service-0.0.1-SNAPSHOT.jar accounts-Microservice.jar
#
##Run the jar file
#ENTRYPOINT ["java","-jar","accounts-Microservice.jar"]