spring:
  application:
    name: "configserver"
  profiles:
    active: git
  #    active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Dibyendu-sk/configs.git
          username: Dibyendu-sk
          password: 123@Dibyendu
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
       #native:
            # to read configration from "configs" folder
          #search-locations: "classpath:/configs"

            #To read configuration from system file path
         #search-locations: "file:///D://codebase/configs"
server:
  port: 8071
